@startuml

[*] --> Новое
Новое --> Подтверждено : Бронирование\nподтверждено\nрестораном
Новое --> Отменено : Бронирование\nне подтверждено\nрестораном
Подтверждено --> Отменено : Бронирование\nотменено\nрестораном
Отменено --> Подтверждено : Ресторан\nподвтердил\nбронирование\nпосле изменения\nусловий
Отменено --> [*]
Подтверждено --> [*]

@enduml