@startuml

Class "Клиент" as client {
    Название
    ИНН
    Состояние
    Наименование
    Тип бизнеса
    Согласен с условиями обработки\nперс данных: boolean
    Закрепленный менеджер
}

class "Представитель\nклиента" as member {
    ФИО
    Телефон
}

class "Тариф" as tariff {
    Наименование
    Мин оборот
    Макс оборот
    Описание
    Комиссия
    Мин количество столиков
    Макс количество столиков
    Стандартный: boolean
}

class "Состояния клиента" as states <<Enumeration>> {
    Новый
    Зарегистрирован
    Активирован
}

class "Типы бизнеса" as business_types <<Enumeration>> {
    Ресторан
}

class "Ресторан" as restaurant {
    Название
    Тип кухни
    Адрес
    Галерея фото
    Расположение: \{
        Долгота,
        Широта
    \}
}

class "Подключение к\nсистеме ресторана" as connection {
    логин
    Пароль
    Сетевой адрес
}

class "Рабочий день" as working_day {
    Время начала
    Время окончания
    День недели
}

class "Столик" as table {
    Количество мест
    Статус
    Описание
}

class "Посетитель" as fl {
    Имя
    Телефон
}

class "Бронирование" as booking {
    Количество гостей
    Дата
    Время
    Статус
    Столик
}

class "Статусы бронирования" as booking_states {
    Новое
    Подтверждено
    Отменено
    Успех
    Неуспех
}

class "Сотрудник плтаформы" as employee {
}

class "Пользователь" as User {
    Email
    Пароль
    Роль
}

member "0..1" --* client
client "0..*" --> "1" tariff
client "0..*" --> "1" states
client "0..*" --> "1" business_types
restaurant "0..*" --* client
connection "0..*" --* restaurant
working_day "0..7" --* restaurant
table "0..*" --* restaurant

booking "0..1" --> "1" booking_states
booking "0..*" --* fl
booking "0..*" -right-> table

employee "0..*" --> "0..*" client
employee "0..*" --> "0..*" tariff

member --|> User
fl --|> User
employee --|> User