@startuml

Actor "Представитель ресторана" as ul

package "Система" {
    usecase "Добавление ресторана" as UC1
    usecase "Редактирование\nинформации\nо ресторане" as UC5

    usecase "Добавление столика" as UC2
    usecase "Оплата услуг" as UC4
    usecase "Просмотр списка\nресторанов" as UC6
    usecase "Просмотр данных\nпрофиля" as UC8
    usecase "Смена пароля" as UC9
    usecase "Просмотр истории оплат" as UC10
    usecase "Просмотр\nкарточки\nресторана" as UC11

    usecase "Авторизация" as UC12
    usecase "Восстановление\nпароля" as UC13
    usecase "Редактирование\nданных профиля" as UC14
    usecase "Удаление ресторана" as UC15
    usecase "Удаление столика" as UC16
}

ul -- UC14
ul -- UC2

UC14 ..> UC12 : <<include>>
UC2 ..> UC12 : <<include>>

UC6 <|-up- UC1
UC6 <|-- UC11
UC11 <|-- UC5
UC2 --|> UC11
UC9 -up-|> UC8
UC10 -up-|> UC8
UC4 -up-|> UC8
UC8 -up-|> UC14
UC16 --|> UC11
UC13 -up-|> UC12 : <<extend>>
UC11 <|-- UC15
UC1 <.up. UC2 : <<include>>

@enduml