@startuml

actor "ФЛ" as fl
package "Система" {
    usecase "Просмотр списка\nресторанов" as UC1
    usecase "Просмотр информации\nо ресторане" as UC2
    usecase "Просмотр списка\nстоликов" as UC3
    usecase "Бронирование\nстолика" as UC4
    usecase "Оставить отзыв" as UC5
    usecase "Просмотр\nрекомендаций" as UC6
    usecase "Смена пароля" as UC7
    usecase "Авторизация" as UC8
    usecase "Регистрация" as UC9

    usecase "Восстановление пароля" as UC10
    usecase "Просмотр профиля" as UC11
    usecase "Поиск столика" as UC12
    usecase "Просмотр списка\nбронирований" as UC13
    usecase "Просмотр активных\nбронирований" as UC14
    usecase "Просмотр брони" as UC15
    usecase "Отмена брони" as UC16
    usecase "Редактирование\nданных профиля" as UC17
}1
1
fl -- UC41
fl -- UC121
fl -- UC141
fl -- UC171
1
' Авторизация1
UC8 <.up. UC12 : <<include>>1
UC8 <.up. UC14 : <<include>>1
UC8 <.up. UC17 : <<include>>1
UC8 <.up. UC4 : <<include>>

UC9 -up-|> UC8 : <<extend>>
UC6 -up-|> UC1 : <<extend>>
UC2 -up-|> UC1
UC3 -up-|> UC4
UC2 -up-|> UC4
UC7 -up-|> UC17 : <<extend>>
UC1 -up-|> UC12
UC10 -up-|> UC8 : <<extend>>
UC14 --|> UC13 : <<extend>>
UC15 -up-|> UC13
UC15 -up-|> UC14
UC5 -up-|> UC15 : <<extend>>
UC16 -up-|> UC15
UC11 -up-|> UC17

@enduml